language: java
jdk:
  - openjdk6
before_script: openssl rsautl -decrypt -inkey ~/.ssh/id_rsa -in private.enc -out private
script:
  - source private
  - mvn clean install ghDownloads:upload -Dgithub.global.userName=$github_global_userName -Dgithub.global.password=$github_global_password
