language: java
jdk:
  - openjdk6
script:
  - sudo apt-get install tree --assume-yes
  - mvn clean deploy -X
  - cd target/repo
  - git init
  - git add .
  - git commit -m "deploy repo"
  - git remote add origin git@github.com:lukewpatterson/travis-deployment-key-demo.wiki.git
  - tree -a
  - git push --force origin master
